Document: node-jscoverage
Title: Debian node-jscoverage Manual
Author: <insert document author here>
Abstract: This manual describes what node-jscoverage is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/node-jscoverage/node-jscoverage.sgml.gz

Format: postscript
Files: /usr/share/doc/node-jscoverage/node-jscoverage.ps.gz

Format: text
Files: /usr/share/doc/node-jscoverage/node-jscoverage.text.gz

Format: HTML
Index: /usr/share/doc/node-jscoverage/html/index.html
Files: /usr/share/doc/node-jscoverage/html/*.html
